@startuml

' !define ENTITY
!define PRIMARY_KEY(x) <b><color:blue>x</color></b>
!define FOREIGN_KEY(x) <color:green>x</color>

hide circle



' Padrones
    ' Children
        ' Users
            ' Gender
            ' Cribroom
            ' Shift
            ' User
            ' Guardian
            ' Children_state
            ' Padron


entity Cribroom {
    + PRIMARY_KEY(id)
    --
    max_capacity
    --
    FOREIGN_KEY(Adress)
    FOREIGN_KEY(Zone)
    FOREIGN_KEY(Shift)
}
' Cribroom muchos a muchos Shift
' Cribroom puede tener mañana y tarde o solo mañana, etc


entity Desinfection {
    + PRIMARY_KEY(id)
    --
    desinfection_date
    company
    company_phone
    --
    FOREIGN_KEY(Cribroom)
}
Desinfection "*" -- "1" Cribroom

entity Payout {
    + PRIMARY_KEY(id)
    --
    amount
    month
    --
    FOREIGN_KEY(Zone)
    ' Payout_Adress = capital or upcountry
}

entity Zone {
    + PRIMARY_KEY(id)
    --
    name
    --

    ' interior or capital
}

Payout "*" - "1" Zone
Zone "1" - "*" Cribroom

entity Child {
    + PRIMARY_KEY(id)
    --
    first_name
    last_name
    dni
    birthdate
    registration_date
    disenroll_date
    --
    FOREIGN_KEY(Gender)
    FOREIGN_KEY(Cribroom)
    FOREIGN_KEY(Shift)
    social_worker = FOREIGN_KEY(User)
    FOREIGN_KEY(Guardian)
    FOREIGN_KEY(Child_state)
}

Cribroom "1" - "*" Child

entity User {
    + PRIMARY_KEY(id)
    --
    username
    password
    --
    FOREIGN_KEY(User_email)
    FOREIGN_KEY(Role)
}

Child "*" - "1" User

entity Guardian {
    + PRIMARY_KEY(id)
    --
    first_name
    last_name
    dni 
    birthdate
    --
    FOREIGN_KEY(Guardian_phone)
    FOREIGN_KEY(Gender)
}

Child "*" -- "1" Guardian


@enduml